    services:
      - type: web
        name: invoice-builder-app
        env: node
        plan: free
        buildCommand: |
          npm install --include=dev
          npm run build
        startCommand: npm start
        envVars:
          - key: NODE_ENV
            value: production
          - key: DATABASE_URL
            fromDatabase:
              name: invoice-builder-db
              property: connectionString
          - key: SESSION_SECRET
            generateValue: true
        autoDeploy: true

    databases:
      - name: invoice-builder-db
        plan: free